// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 負責管理應用程式設定的讀取、修改與寫入
 * 
 * ~/Library/Application Support/VideoConverter/config.json
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * 取得 FFmpeg 路徑
 */
export function GetFFmpegPath(): $CancellablePromise<string> {
    return $Call.ByID(2070138830);
}

/**
 * 儲存 FFmpeg 路徑
 */
export function SetFFmpegPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(687620594, path);
}
