// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FFmpegService 封裝 FFmpeg 轉換流程與狀態管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * 嘗試取消目前正在執行的 FFmpeg 轉換
 *   - 函式會先檢查目前是否有可取消的轉換，再透過 FFmpeg 的標準輸入傳送 "q" 指令，讓 FFmpeg 有機會正常完成輸出檔案的收尾工作
 *   - FFmpeg 讀取 stdin 時收到 q，會停止轉檔並正常寫 trailer
 *   - 如果 FFmpeg 在 5 秒內仍未結束，則由背景程序強制終止 FFmpeg
 *   - 以下任一條件成立時，就不能取消：
 *     1. 沒有正在執行的轉換。
 *     2. 已經正在取消中，避免重複送出取消指令。
 *     3. 沒有 FFmpeg 的標準輸入管道。
 *     4. 沒有目前執行中的 FFmpeg 命令。
 * 
 * 回傳：
 *   - true 表示取消要求已成功送出
 *   - false 表示目前沒有可取消的轉換，或無法將取消指令寫入 FFmpeg 的標準輸入
 */
export function CancelConversion(): $CancellablePromise<boolean> {
    return $Call.ByID(603568877);
}

/**
 * 取得目前 FFmpeg 轉換的狀態
 *   - 函式會使用互斥鎖保護共享狀態，避免在其他 goroutine 修改狀態時讀取到不一致的資料
 */
export function GetConversionState(): $CancellablePromise<$models.ConversionState> {
    return $Call.ByID(447325734);
}

/**
 * GetVideoDuration 使用 ffprobe 取得影片長度，單位為秒。
 * 
 * 回傳：
 * - duration：影片長度，例如 180.52 秒
 * - error：ffprobe 執行失敗或輸出格式無法解析
 */
export function GetVideoDuration(ffmpegPath: string, inputPath: string): $CancellablePromise<number> {
    return $Call.ByID(884924980, ffmpegPath, inputPath);
}

/**
 * StartConversion 啟動一次 FFmpeg 影片轉換工作
 *   - 函式會先驗證輸入檔案，接著建立輸出路徑與 FFmpeg 參數，然後啟動 FFmpeg 並即時讀取其 stderr 輸出
 *   - 不使用 -nostdin，才能在取消時對 FFmpeg 寫入 `q`
 *   - 如果轉換期間收到取消要求，函式會等待 FFmpeg 嘗試正常結束
 *   - 如果 FFmpeg 在指定時間內仍未結束，則會強制終止 FFmpeg 程序
 * 
 * 回傳：
 *   - 轉換成功時，回傳 ConversionResult 與 nil 錯誤
 *   - 轉換失敗時，回傳空的 ConversionResult 與錯誤訊息
 */
export function StartConversion(options: $models.ConversionOptions): $CancellablePromise<$models.ConversionResult> {
    return $Call.ByID(2954419465, options);
}
