// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversionOptions 定義影片轉換時所需的設定
 */
export interface ConversionOptions {
    /**
     * InputPath 是輸入影片的檔案路徑
     */
    "inputPath": string;

    /**
     * FFmpegPath 是 FFmpeg 執行檔的路徑；例如："/usr/local/bin/ffmpeg"
     */
    "ffmpegPath": string;

    /**
     * Container 是輸出的容器格式；例如："mp4"、"mov" 或 "mkv"
     */
    "container": string;

    /**
     * VideoCodec 是使用的影片編碼器；例如："libx264"、"libx265" 或 "libvpx-vp9"
     */
    "videoCodec": string;

    /**
     * StartTime 是剪輯或轉換的開始時間；通常使用 FFmpeg 支援的時間格式，例如："00:01:30"
     */
    "startTime": string;

    /**
     * EndTime 是剪輯或轉換的結束時間；通常使用 FFmpeg 支援的時間格式，例如："00:05:00"
     */
    "endTime": string;

    /**
     * Width 是輸出影片的寬度，單位為像素
     */
    "width": number;

    /**
     * Height 是輸出影片的高度，單位為像素
     */
    "height": number;

    /**
     * UseStart 表示是否套用 StartTime
     */
    "useStart": boolean;

    /**
     * UseEnd 表示是否套用 EndTime
     */
    "useEnd": boolean;

    /**
     * UseSize 表示是否套用 Width 和 Height 進行縮放
     */
    "useSize": boolean;
}

/**
 * ConversionResult 表示影片轉換完成後的結果
 */
export interface ConversionResult {
    /**
     * OutputPath 是轉換後輸出檔案的路徑
     */
    "outputPath": string;

    /**
     * Message 是提供給前端或使用者閱讀的結果訊息
     */
    "message": string;
}

/**
 * ConversionState 表示目前影片轉換工作的狀態；此結構通常會序列化成 JSON 後傳送給前端
 */
export interface ConversionState {
    /**
     * Running 表示目前是否正在執行轉換
     */
    "running": boolean;

    /**
     * Cancelling 表示是否正在等待取消操作完成
     */
    "cancelling": boolean;

    /**
     * Cancelled 表示轉換是否已經被取消
     */
    "cancelled": boolean;
}
